[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/"
  [headers.values]
    Link = '''
    </assets/css/style.css>; rel=preload; as=style,
    </assets/img/favicon.ico>; rel=preload; as=image,
    </assets/img/logo.png>; rel=preload; as=image,
    </assets/js/google-analytics.js>; rel=preload; as=script'''
